routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','front\WebsiteController@index');
Route::get('/search','front\WebsiteController@search');
Route::get('/get-districts','front\WebsiteController@districts');
Route::get('/get-subdistricts/{district_id}', 'front\WebsiteController@subDistricts');
//Institute routes
Route::get('/institutes','front\WebsiteController@institutes');
Route::get('/institute/{id}','front\WebsiteController@showInstitute');
Route::post('/search-institute','front\WebsiteController@searchInstitute');
Route::get('/filter-institutes','front\WebsiteController@filterInstitute');
Route::get('/institute-compare','front\WebsiteController@instituteCompare');
//Hospital routes
Route::get('/hospitals','front\WebsiteController@hospitals');
Route::get('/hospital/{id}','front\WebsiteController@showHospital');
Route::post('/search-hospital','front\WebsiteController@searchHospital');
Route::get('/filter-hospitals','front\WebsiteController@filterHospital');
Route::get('/hospital-compare','front\WebsiteController@hospitalCompare');
//Hotel rountes
Route::get('/hotels','front\WebsiteController@hotels');
Route::get('/hotel/{id}','front\WebsiteController@showhotel');
Route::post('/search-hotel','front\WebsiteController@searchHotel');
Route::get('/filter-hotels','front\WebsiteController@filterHotel');
Route::get('/hotel-compare','front\WebsiteController@hotelCompare');
//Tour Place route
Route::get('/tour-places','front\WebsiteController@tourPlaces');
Route::get('/tour-place/{id}','front\WebsiteController@showTourPlace');
Route::post('/search-tour-place','front\WebsiteController@searchTourPlace');
//Route::post('/filter-tour-places','front\WebsiteController@filterTourPlace');
Route::get('/tour-place-compare','front\WebsiteController@tourPlaceCompare');

Auth::routes();
Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');
Route::get('/discuss', 'Forum\ForumController@index')->name('forum');
Route::get('/single', 'Forum\ForumController@single');
Route::resource('discuss/post','Forum\ForumController');
Route::get('/discuss/category-post/{id}', 'Forum\ForumController@category_posts');
Route::post('/discuss/comment', 'Forum\ForumController@storeComment');
Route::post('/search-question','Forum\ForumController@searchQuestion');
Route::get('{path}',"HomeController@index")->where( 'path', '([A-z\d-\/_.]+)?' )->middleware('verified');

app/Forum.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Forum extends Model
{
    protected $fillable = [
        'id','name','description','category_id','email','isActive',
    ];
    public function comments()
    {
        return $this->hasMany('App\ForumComments');
    }
    public function category()
    {
        return $this->belongsTo(Category::class);
    }
}

app/Http/Controllers/API/ForumController.php
<?php

namespace App\Http\Controllers\API;

use App\Forum;
use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ForumController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:api');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (\Gate::allows('isAdminOrAuthorOrEditor')) {
            //return Forum::latest()->paginate(10);
            return Forum::orderBy('isActive','Pending')->orderBy('created_at','ASC')->paginate(10);
        }

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $Forum = Forum::findOrFail($id);
        $Forum->update($request->all());
        return ['update' => "Forum information updated"];
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $Forum = Forum::findOrFail($id);
        $Forum->delete();
        return ['delete'=>"Deleted successfully"];
    }
    public function search(){
        if ($search = \Request::get('q')) {
            $forumPosts = Forum::where(function($query) use ($search){
                $query->where('name','LIKE',"%$search%");
                $query->orWhere('description','LIKE',"%$search%");
                $query->orWhere('isActive','LIKE',"%$search%");
            })->orderBy('isActive','Pending')->orderBy('created_at','ASC')->paginate(10);
        }else{
            $forumPosts = Forum::orderBy('isActive','Pending')->orderBy('created_at','ASC')->paginate(10);
        }

        return $forumPosts;
    }
}

app/Http/Controllers/Forum/ForumController.php
<?php
namespace App\Http\Controllers\Forum;
use App\Category;
use App\Forum;
use App\ForumComments;
use Validator;
use Illuminate\Http\Response;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
class ForumController extends Controller
{
    public function index()
    {
        $forumPosts = Forum::withCount('comments')->where('isActive','=','Active')->latest()->paginate(15);
        return view('forum.home',['forumPosts'=>$forumPosts]);
    }
    public function create()
    {
        $categories = Category::where('isActive','=','Active')->orderby('name','asc')->get();
        return view('forum.new',['categories'=>$categories]);
    }
    public function store(Request $request)
    {
        if($request->ajax())
        {
            $validator = Validator::make($request->all(),[
                'name'=>'required|string|max:100',
                'category_id'=>'required',
                'description'=>'required|string',
            ]);
            if($validator->fails())
            {
                return response()->json(
                    [
                        'error'=>true,
                        'message'=>$validator->messages(),
                        'code'=>400
                    ],400);
            };

            //$unique_id = time().rand(100000,10000000);

            DB::table('forums')->insert([
                'name'=>$request->name,
                'category_id'=>$request->category_id,
                'description'=>$request->description,
            ]);
            //return redirect('/discuss/post/create')->with('message','You have successfully uploaded you post, we will review it and after then we publish it in public!');
            return ['success'=> "You question submitted"];
        }
    }
    public function storeComment(Request $request)
    {
        if($request->ajax())
        {
            $validator = Validator::make($request->all(),[
                'name'=>'required|string|max:100',
                'reply'=>'required|string',
            ]);
            if($validator->fails())
            {
                return response()->json(
                    [
                        'error'=>true,
                        'message'=>$validator->messages(),
                        'code'=>400
                    ],400);
            };
            //$unique_id = time().rand(100000,10000000);
            //ForumComments::insert($request->all());
            DB::table('forum_comments')->insert([
                'name'=>$request->name,
                'forum_id'=>$request->forum_id,
                'reply'=>$request->reply
            ]);
            return ['message','Thanks for your reply !'];
        }
    }
    public function show($id)
    {
        $post = Forum::findOrfail($id);
        DB::table('forums')->where('id',$id)->increment('views');
        $comments = ForumComments::where('forum_id',$id)->latest()->paginate(8);
        return view('forum.single',['post'=>$post,'comments'=>$comments]);
    }
    public function category_posts($catId)
    {
        $posts = Forum::where('category_id', $catId)->where('isActive','=','Active')->latest()->paginate(15);
        return view('forum.category_posts',['forumPosts'=> $posts]);
    }
    public function searchQuestion(Request $request)
    {
        $id = $request->id;
        return redirect('discuss/post/'.$id);
    }
}

resources/views/forum/category_posts.blade.php
@extends('forum.master')
@section('title')
Discussion Forum - BestInBd
@endsection
@section('content')
    <div class="col-lg-8 col-md-8">
        <!-- POST -->
        <h2></h2>
        @foreach($forumPosts as $post)
        <div class="post">
            <div class="wrap-ut pull-left">
                <div class="posttext pull-left">
                    <img src="{{asset('forum/images/avatar.png')}}" alt="" style="margin-right:20px;margin-top:-10px;"/>
                    <h3 style="display:inline-block"><a href="{{ url('/discuss/post/'.$post->id)}}" style="text-decoration:none;display:inline-block">{{$post->name}}</a></h3>
                    <h2><a href="{{ url('/discuss/post/'.$post->id)}}">{{$post->title}}</a></h2>
                    <a href="{{ url('/discuss/post/'.$post->id)}}" style="text-decoration:none;">{{$post->description}}.</a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="postinfo pull-left">
                <div class="comments">
                    <div class="commentbg">
                        89
                        <div class="mark"></div>
                    </div>

                </div>
                <div class="views"><a href="{{ url('/discuss/post/'.$post->id)}}" style="text-decoration:none;"><i class="fa fa-eye"></i> {{$post->views}}</a></div>
                <div class="time"><i class="fa fa-clock-o"></i> {{$post->created_at->diffForHumans()}}</div>                                    
            </div>
            <div class="clearfix"></div>
        </div><!-- POST -->
        @endforeach
        {{ $forumPosts->links() }}
    </div>
@endsection

resources/views/forum/home.blade.php
@extends('forum.master')
@section('title')
Discussion Forum - BestInBd
@endsection
@section('content')
    <div class="col-lg-8 col-md-8">
        <!-- POST -->
        @foreach($forumPosts as $post)
        <div class="post">
            <div class="wrap-ut pull-left">
                <div class="posttext pull-left">
                @if($post->id % 2 == 0)
                    <img src="{{asset('forum/images/avatar.png')}}" alt="" style="margin-right:20px;margin-top:-10px;"/>
                @else
                    <img src="{{asset('forum/images/avatar3.png')}}" alt="" style="margin-right:20px;margin-top:-10px;"/>
                @endif
                    <h2 class="questioner_name"><a href="{{ url('/discuss/post/'.$post->id)}}" style="text-decoration:none">{{$post->name}}</a></h2>
                    <a href="{{ url('/discuss/post/'.$post->id)}}" class="post_description">{{str_limit($post->description,250)}}</a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="postinfo pull-left" title="Answer of peoples">
                <div class="comments">
                    <div class="commentbg">
                        {{$post->comments_count}}
                        <div class="mark"></div>
                    </div>
                </div>
                <div class="views"><a href="{{ url('/discuss/post/'.$post->id)}}" style="text-decoration:none;"><i class="fa fa-eye"></i> {{$post->views}}</a></div>
                <div class="time"><i class="fa fa-clock-o"></i> {{$post->created_at->diffForHumans()}}</div>                                    
            </div>
            <div class="clearfix"></div>
        </div><!-- POST -->
        @endforeach
        {{ $forumPosts->links() }}
    </div>

@endsection

resources/views/forum/new.blade.php
@extends('forum.master')
@section('title')
Add New Discuss - BestInBd
@endsection
@section('content')
    <div class="col-lg-8 col-md-8">
        @if($message = Session::get('message'))
            <p class="alert" style="font-weight: 500;font-size: 16px;background-color: #61d864;padding:12px;color:#fff;margin-top: 1px;position:fixed;right: 50px;z-index: 1">{{ $message }}</p>
        @endif
        <!-- POST -->
        <div class="post">
            <h2 style="color:green;" id="successMessage" class="alert">Write Down Your Question?</h2>
            <form action="{{url('/discuss/post')}}" class="form newtopic" method="post" id='postCreate'>
               
                <div class="topwrap">
                    <div class="posttext pull-left">

                        <div>
                            <input type="text" name="name" placeholder="Your Name *" class="form-control" autocomplete="on" required/>
                            <span class="error">
                                    <strong style="color: red;" id="nameErrorMsg"></strong>
                            </span>
                        </div>
                        <div>
                            <small>(Optional) We will send you an email that will say your post is published or not</small>
                            <input type="text" name="email" placeholder="Your Email" class="form-control" />
                            <span class="error">
                                    <strong style="color: red;" id="emailErrorMsg"></strong>
                            </span>
                        </div>

                        <div class="row">
                            <div class="col-lg-12 col-md-12">
                                <select name="category_id" id="category"  class="form-control" required>
                                    <option value="" disabled selected>Select Category *</option>
                                    @foreach($categories as $category)
                                        <option value="{{$category->id}}">{{$category->name}}</option>
                                    @endforeach
                                </select>
                                <span class="error">
                                        <strong style="color: red;" id="categoryErrorMsg"></strong>
                                    </span>
                            </div>
                        </div>

                        <div>
                            <textarea name="description" id="desc" placeholder="Description *"  class="form-control" required></textarea>
                            <span class="error">
                                    <strong style="color: red;" id="descriptionErrorMsg"></strong>
                                </span>
                        </div>


                    </div>
                    <div class="clearfix"></div>
                </div>                              
                <div class="postinfobot">

                    <div class="pull-right postreply">
                        <div class="pull-left smile"><a href="#"><i class="fa fa-smile-o"></i></a></div>
                        <div class="pull-left"><input type="submit" class="btn btn-primary" value='Submit'></div>
                        <div class="clearfix"></div>
                    </div>


                    <div class="clearfix"></div>
                </div>
            </form>
        </div><!-- POST -->
    </div>
@endsection
@section('script')

@endsection

resources/views/forum/single.blade.php
@extends('forum.master')
@section('content')
    <div class="col-lg-8 col-md-8">
        <!-- POST -->
        <div class="post beforepagination">
            <div class="topwrap">
                <div class="posttext pull-left">
                    @if($post->id % 2 == 0)
                        <img src="{{asset('forum/images/avatar.png')}}" alt="" style="margin-right:20px;margin-top:-10px;"/>
                    @else
                        <img src="{{asset('forum/images/avatar3.png')}}" alt="" style="margin-right:20px;margin-top:-10px;"/>
                    @endif
                    <h3 style="display:inline-block;">{{$post->name}}</h3>
                    <h2>{{$post->title}}</h2>
                    <p>{{$post->description}}</p>
                </div>
                <div class="clearfix"></div>
            </div>                              
            <div class="postinfobot">

                <div class="likeblock pull-left">
                    <a href="#" class="up"><i class="fa fa-thumbs-o-up"></i>25</a>
                    <a href="#" class="down"><i class="fa fa-thumbs-o-down"></i>3</a>
                </div>

                <div class="prev pull-left">                                        
                    <a href="#"><i class="fa fa-reply"></i></a>
                </div>

                <div class="posted pull-left"><i class="fa fa-clock-o"></i> Posted on : {{$post->created_at->toDayDateTimeString()}}</div>

                <div class="next pull-right">                                        
                    <a href="#"><i class="fa fa-share"></i></a>

                    <a href="#"><i class="fa fa-flag"></i></a>
                </div>

                <div class="clearfix"></div>
            </div>
        </div><!-- POST -->


        <!--Replay POST -->
        <div class="post">
            <form action="{{url('/discuss/comment')}}" class="form" method="post" id="commentForm">
                <div class="topwrap">
                    <div class="posttext pull-left">
                            <h2>Post a Reply</h2>
                            <div class="form-group">
                                <input type="text" name="name" placeholder="Your Name *" class="form-control" autocomplete="on"/>
                                <input type="hidden" name="forum_id" value="{{$post->id}}"/>
                                <span class="error">
                                    <strong style="color: red;" id="nameErrorMssg"></strong>
                                </span>
                            </div>
                            <div class="form-group">
                                <textarea name="reply" class="form-control" id="reply" placeholder="Type your message here *"></textarea>
                                <span class="error">
                                    <strong style="color: red;" id="replyErrorMsg"></strong>
                                </span>
                            </div>
                    </div>
                    <div class="clearfix"></div>
                </div>                              
                <div class="postinfobot">

                    <div class="notechbox pull-left">
                        <!--<input type="checkbox" name="note" id="note" class="form-control" />-->
                    </div>

                    <div class="pull-left">
                        <!--<label for="note"> Email me when some one post a reply</label>-->
                    </div>

                    <div class="pull-right postreply">
                        <div class="pull-left smile"><a href="javascript:void(0)"><i class="fa fa-smile-o"></i></a></div>
                        <div class="pull-left"><button type="submit" class="btn btn-primary">Post Reply</button></div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </form>
        </div><!-- Replay POST -->
        @foreach ($comments as $comment)
        <!-- POST -->
        <div class="post">
            <div class="topwrap">
                <div class="posttext pull-left">
                    @if($comment->id % 2 == 0)
                        <img src="{{asset('forum/images/avatar4.png')}}" alt="" style="margin-right:20px;margin-top:-10px;"/>
                    @else
                        <img src="{{asset('forum/images/avatar6.png')}}" alt="" style="margin-right:20px;margin-top:-10px;"/>
                    @endif
                    <h3 style="display:inline-block;">{{$comment->name}}</h3>
                    <p>{{$comment->reply}}</p>
                </div>
                <div class="clearfix"></div>
            </div>                              
            <div class="postinfobot">

                <div class="likeblock pull-left">
                    <a href="#" class="up"><i class="fa fa-thumbs-o-up"></i>10</a>
                    <a href="#" class="down"><i class="fa fa-thumbs-o-down"></i>1</a>
                </div>

                <div class="prev pull-left">                                        
                    <a href="#"><i class="fa fa-reply"></i></a>
                </div>

                <div class="posted pull-left"><i class="fa fa-clock-o"></i> Posted on : <?php if(!empty($comment->created_at)) echo $comment->created_at->toDayDateTimeString()?></div>

                <div class="next pull-right">                                        
                    <a href="#"><i class="fa fa-share"></i></a>

                    <a href="#"><i class="fa fa-flag"></i></a>
                </div>

                <div class="clearfix"></div>
            </div>
        </div><!-- POST -->
        @endforeach
        {{ $comments->links() }}
    </div>
@endsection
@section('script')

<script>
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
    $('#commentForm').on('submit',function (e) {
        e.preventDefault();
        var data = $(this).serialize();
        var url = $(this).attr('action');
        $.ajax({
            type:'post',
            url:url,
            data:data,
            dataTy:'json',
            success:function (data) {
                $('#commentForm').trigger('reset');
                swal({
                    title: "You have successfully added your reply, Thank You?",
                    icon: "success",
                })
                .then((value) => {
                    if (value) {
                        $('#questionModal').modal('hide');
                        location.reload();
                    }else{
                        $('#questionModal').modal('hide');
                        location.reload();
                    }
                });
                /*swal({
                    title: "You have successfully added your reply, Thank You?",
                    icon: "success",
                    buttons: true,
                    })
                    .then((willDelete) => {
                    if (willDelete) {
                        $('#questionModal').modal('hide');
                        location.reload();
                    }
                });*/
            },
            error:function (errorData) {
                var error = errorData.responseJSON.message;
                $('#nameErrorMssg').html('');
                $('#replyErrorMsg').html('');

                $('#nameErrorMssg').append(error['name']);
                $('#replyErrorMsg').append(error['reply']);
            }
        });
    });
    
</script>
<script>
        <!--
        function timedRefresh(timeoutPeriod) {
            setTimeout("location.reload(true);",timeoutPeriod);
        }
        //window.onload = timedRefresh(5000);
</script>
@endsection